In [14]:
import pandas as pd

In [5]:
df = pd.read_pickle(f"../dataset/3p6.pkl", compression='zip')

In [6]:
df.head()

       x     y     z    vx    vy   vz    px    py    pz  time  distance
0 -117.0  87.0 -33.0  0.46  0.02 -0.0  2.47 -2.39 -0.49   363     150.0
1 -113.0  87.0 -33.0  0.46  0.02  0.0  2.54 -2.25 -0.54   363     146.0
2 -109.0  87.0 -33.0  0.47  0.03  0.0  2.44 -2.00 -0.58   363     143.0
3 -105.0  87.0 -33.0  0.47  0.03  0.0  2.21 -1.68 -0.61   363     140.0
4 -101.0  87.0 -33.0  0.47  0.03  0.0  1.89 -1.36 -0.60   363     137.0

In [15]:
df1 = pd.read_pickle(f"../dataset/3p6-selected.pkl", compression='zip')

In [16]:
df1.head()

             x     y     z    vx    vy    vz    px    py    pz  time  distance
1824696 -117.0  87.0 -33.0  0.48  0.02  0.04 -0.57 -0.11 -2.17   301     150.0
1824697 -113.0  87.0 -33.0  0.48  0.02  0.04 -0.50 -0.40 -2.10   301     146.0
1824698 -109.0  87.0 -33.0  0.48  0.02  0.04 -0.45 -0.58 -2.01   301     143.0
1824699 -105.0  87.0 -33.0  0.48  0.02  0.04 -0.42 -0.67 -1.91   301     140.0
1824700 -101.0  87.0 -33.0  0.48  0.02  0.05 -0.36 -0.69 -1.80   301     137.0

In [17]:
df1.shape

(304116, 11)

In [18]:
df_labels = df1[(df1["time"]==303) & (df1["distance"]==150)]

In [21]:
df_labels.shape

(59, 11)

In [22]:
df_labels

,x,y,z,vx,vy,vz,px,py,pz,time,distance
25697802,-117.0,87.0,-33.0,0.48,0.01,0.03,0.55,0.52,-1.55,303,150.0
25697865,-121.0,83.0,-33.0,0.49,0.02,0.03,0.55,1.30,-1.20,303,150.0
25697926,121.0,83.0,-33.0,0.48,0.00,0.14,1.04,-3.33,4.84,303,150.0
25697992,-125.0,75.0,-33.0,0.50,0.02,0.03,1.14,2.21,-0.73,303,150.0
25700424,-125.0,-76.0,-33.0,0.49,-0.02,0.04,-1.39,-3.97,-0.94,303,150.0
25700614,121.0,-83.0,-33.0,0.43,-0.03,0.08,3.04,1.08,2.96,303,150.0
25700681,-121.0,83.0,-29.0,0.50,0.01,0.04,0.41,1.18,-1.58,303,150.0
25700807,125.0,79.0,-29.0,0.48,0.01,0.16,1.35,-3.40,4.07,303,150.0
25703369,-121.0,-83.0,-29.0,0.49,-0.01,0.02,-1.73,-3.28,-3.84,303,150.0
25703430,121.0,-83.0,-29.0,0.44,-0.04,0.09,3.18,0.76,2.98,303,150.0
25703560,-125.0,79.0,-25.0,0.51,0.01,0.05,0.33,1.71,-1.41,303,150.0
25703623,125.0,79.0,-25.0,0.48,0.01,0.16,0.82,-2.96,3.76,303,150.0
25706120,-125.0,-80.0,-25.0,0.50,-0.02,0.04,-1.15,-2.66,-4.53,303,150.0
25706183,125.0,-80.0,-25.0,0.43,-0.04,0.09,3.55,0.16,2.65,303,150.0
25706310,121.0,87.0,-21.0,0.48,0.02,0.15,0.62,-2.28,5.24,303,150.0
25708936,-125.0,-80.0,-21.0,0.50,-0.02,0.04,-0.77,-1.96,-5.47,303,150.0
25709065,-121.0,87.0,-17.0,0.50,-0.00,0.07,-0.15,0.35,-1.81,303,150.0
25709126,121.0,87.0,-17.0,0.48,0.02,0.15,0.39,-1.42,5.27,303,150.0
25711881,-121.0,87.0,-13.0,0.50,-0.00,0.08,-0.13,-0.01,-1.71,303,150.0
25712007,125.0,83.0,-13.0,0.48,0.03,0.16,-0.26,-0.39,4.21,303,150.0
25714760,-125.0,83.0,-9.0,0.51,0.01,0.09,-0.20,0.04,-1.31,303,150.0
25714823,125.0,83.0,-9.0,0.49,0.04,0.15,-0.35,0.46,4.11,303,150.0
25717511,125.0,-83.0,-9.0,0.44,-0.05,0.10,2.85,-0.84,2.78,303,150.0
25717576,-125.0,83.0,-5.0,0.50,0.01,0.10,-0.12,-0.45,-1.45,303,150.0
25717639,125.0,83.0,-5.0,0.49,0.04,0.15,-0.32,1.20,3.93,303,150.0
25720264,-125.0,-83.0,-5.0,0.47,-0.04,0.03,1.46,0.49,-7.34,303,150.0
25720327,125.0,-83.0,-5.0,0.45,-0.05,0.10,2.80,-0.93,2.56,303,150.0
25720392,-125.0,83.0,-1.0,0.49,0.02,0.11,-0.05,-0.92,-1.82,303,150.0
25720455,125.0,83.0,-1.0,0.50,0.05,0.15,-0.19,1.78,3.66,303,150.0
25723080,-125.0,-83.0,-1.0,0.47,-0.04,0.02,2.10,1.18,-7.16,303,150.0
25723143,125.0,-83.0,-1.0,0.45,-0.04,0.10,2.87,-0.97,2.35,303,150.0
25723208,-125.0,83.0,3.0,0.48,0.03,0.11,-0.06,-1.35,-2.37,303,150.0
25723271,125.0,83.0,3.0,0.50,0.05,0.14,0.02,2.20,3.31,303,150.0
25725896,-125.0,-83.0,3.0,0.47,-0.04,0.02,2.73,1.90,-6.92,303,150.0
25725959,125.0,-83.0,3.0,0.45,-0.04,0.09,3.03,-0.97,2.14,303,150.0
25726024,-125.0,83.0,7.0,0.47,0.04,0.11,-0.19,-1.72,-2.93,303,150.0
25726087,125.0,83.0,7.0,0.50,0.05,0.14,0.27,2.49,2.94,303,150.0
25728775,125.0,-83.0,7.0,0.46,-0.03,0.09,3.26,-0.95,1.93,303,150.0
25728840,-125.0,83.0,11.0,0.46,0.05,0.11,-0.42,-2.02,-3.36,303,150.0
25728903,125.0,83.0,11.0,0.50,0.05,0.13,0.50,2.66,2.60,303,150.0
25731591,125.0,-83.0,11.0,0.46,-0.02,0.08,3.49,-0.94,1.70,303,150.0
25731593,-121.0,87.0,14.0,0.45,0.05,0.11,-0.40,-3.05,-4.23,303,150.0
25731719,125.0,83.0,14.0,0.49,0.05,0.12,0.66,2.73,2.26,303,150.0
25734409,-121.0,87.0,18.0,0.45,0.06,0.11,-0.66,-3.41,-4.39,303,150.0
25734470,121.0,87.0,18.0,0.49,0.05,0.12,0.50,2.88,1.86,303,150.0
25737286,121.0,87.0,22.0,0.48,0.05,0.11,0.62,2.84,1.65,303,150.0
25737352,-125.0,79.0,22.0,0.44,0.05,0.10,-1.32,-2.56,-3.16,303,150.0
25739912,-125.0,-80.0,22.0,0.47,-0.03,-0.02,5.94,5.33,-5.36,303,150.0
25740168,-125.0,79.0,26.0,0.44,0.05,0.09,-1.63,-3.10,-3.13,303,150.0
25740231,125.0,79.0,26.0,0.48,0.04,0.10,0.70,2.57,1.69,303,150.0
25742791,125.0,-80.0,26.0,0.46,-0.01,0.06,3.88,-1.28,0.71,303,150.0
25742921,-121.0,83.0,30.0,0.44,0.05,0.09,-1.42,-4.28,-4.13,303,150.0
25745609,-121.0,-83.0,30.0,0.48,-0.02,-0.02,6.49,6.96,-5.12,303,150.0
25745670,121.0,-83.0,30.0,0.46,-0.01,0.06,3.17,-1.56,0.84,303,150.0
25745674,-117.0,87.0,34.0,0.45,0.05,0.08,-0.91,-5.24,-5.20,303,150.0
25745798,121.0,83.0,34.0,0.47,0.04,0.08,1.03,2.49,1.85,303,150.0
25745864,-125.0,75.0,34.0,0.44,0.05,0.07,-1.94,-4.06,-2.90,303,150.0
25748296,-125.0,-76.0,34.0,0.48,-0.02,-0.03,6.85,7.26,-3.49,303,150.0
25748359,125.0,-76.0,34.0,0.46,-0.01,0.04,3.76,-1.60,0.23,303,150.0

In [23]:
df_labels.to_csv("../dataset/3p6-selected-test.csv", index=False)

In [29]:
df_labels.to_pickle(f"../dataset/3p6-selected-test.pkl", compression='zip')

In [26]:
df_labels1 = df_labels.drop(df_labels.columns.difference(["x","y","z","time"]), axis=1)

In [27]:
df_labels1

              x     y     z  time
25697802 -117.0  87.0 -33.0   303
25697865 -121.0  83.0 -33.0   303
25697926  121.0  83.0 -33.0   303
25697992 -125.0  75.0 -33.0   303
25700424 -125.0 -76.0 -33.0   303
25700614  121.0 -83.0 -33.0   303
25700681 -121.0  83.0 -29.0   303
25700807  125.0  79.0 -29.0   303
25703369 -121.0 -83.0 -29.0   303
25703430  121.0 -83.0 -29.0   303
25703560 -125.0  79.0 -25.0   303
25703623  125.0  79.0 -25.0   303
25706120 -125.0 -80.0 -25.0   303
25706183  125.0 -80.0 -25.0   303
25706310  121.0  87.0 -21.0   303
25708936 -125.0 -80.0 -21.0   303
25709065 -121.0  87.0 -17.0   303
25709126  121.0  87.0 -17.0   303
25711881 -121.0  87.0 -13.0   303
25712007  125.0  83.0 -13.0   303
25714760 -125.0  83.0  -9.0   303
25714823  125.0  83.0  -9.0   303
25717511  125.0 -83.0  -9.0   303
25717576 -125.0  83.0  -5.0   303
25717639  125.0  83.0  -5.0   303
25720264 -125.0 -83.0  -5.0   303
25720327  125.0 -83.0  -5.0   303
25720392 -125.0  83.0  -1.0   303
25720455  125.0  83.0  -1.0   303
25723080 -125.0 -83.0  -1.0   303
25723143  125.0 -83.0  -1.0   303
25723208 -125.0  83.0   3.0   303
25723271  125.0  83.0   3.0   303
25725896 -125.0 -83.0   3.0   303
25725959  125.0 -83.0   3.0   303
25726024 -125.0  83.0   7.0   303
25726087  125.0  83.0   7.0   303
25728775  125.0 -83.0   7.0   303
25728840 -125.0  83.0  11.0   303
25728903  125.0  83.0  11.0   303
25731591  125.0 -83.0  11.0   303
25731593 -121.0  87.0  14.0   303
25731719  125.0  83.0  14.0   303
25734409 -121.0  87.0  18.0   303
25734470  121.0  87.0  18.0   303
25737286  121.0  87.0  22.0   303
25737352 -125.0  79.0  22.0   303
25739912 -125.0 -80.0  22.0   303
25740168 -125.0  79.0  26.0   303
25740231  125.0  79.0  26.0   303
25742791  125.0 -80.0  26.0   303
25742921 -121.0  83.0  30.0   303
25745609 -121.0 -83.0  30.0   303
25745670  121.0 -83.0  30.0   303
25745674 -117.0  87.0  34.0   303
25745798  121.0  83.0  34.0   303
25745864 -125.0  75.0  34.0   303
25748296 -125.0 -76.0  34.0   303
25748359  125.0 -76.0  34.0   303

In [30]:
gen = pd.read_csv("../logs/cgan.csv")

In [31]:
gen

,x,y,z,time,vx,vy,vz,px,py,pz,distance
0,-117.0,87.0,-33.0,303.0,0.526974,-0.049908,0.149607,2.046381,11.025826,-6.478140,149.58998
1,-121.0,83.0,-33.0,303.0,0.530566,-0.052305,0.256743,9.901219,10.893388,-6.332528,149.78200
2,121.0,83.0,-33.0,303.0,0.499156,-0.039291,0.014285,3.223594,17.503960,-3.736727,149.44662
3,-125.0,75.0,-33.0,303.0,0.518032,-0.050299,0.212605,7.839618,11.800776,-4.667294,149.64316
4,-125.0,-76.0,-33.0,303.0,0.523402,-0.058345,0.447390,5.733462,4.780064,-2.159719,149.98154
5,121.0,-83.0,-33.0,303.0,0.500581,-0.039297,0.235605,5.047581,6.992388,-0.600316,149.91756
6,-121.0,83.0,-29.0,303.0,0.530456,-0.050478,0.114868,0.058061,13.109960,-7.850201,149.50507
7,125.0,79.0,-29.0,303.0,0.505257,-0.043360,-0.005315,2.342449,14.992518,-3.687363,149.43720
8,-121.0,-83.0,-29.0,303.0,0.520845,-0.046682,0.371753,6.674101,3.893335,-1.495084,149.96129
9,121.0,-83.0,-29.0,303.0,0.509646,-0.035638,0.181266,6.413943,7.287382,-1.641035,149.72226
10,-125.0,79.0,-25.0,303.0,0.525029,-0.045233,0.219136,5.643926,9.622766,-4.958944,149.59576
11,125.0,79.0,-25.0,303.0,0.501793,-0.049415,0.025441,2.108274,17.071104,-3.572907,149.44179
12,-125.0,-80.0,-25.0,303.0,0.511416,-0.051458,0.345282,5.221449,5.150988,-1.518474,150.03954
13,125.0,-80.0,-25.0,303.0,0.486708,-0.040283,0.223147,15.463180,9.827970,2.774469,149.89084
14,121.0,87.0,-21.0,303.0,0.506879,-0.036924,0.013915,5.832999,15.210878,-4.244336,149.35250
15,-125.0,-80.0,-21.0,303.0,0.522925,-0.050286,0.334967,6.078442,4.616536,-2.308834,149.98909
16,-121.0,87.0,-17.0,303.0,0.532390,-0.047731,0.245860,8.367107,8.028394,-5.596762,149.81110
17,121.0,87.0,-17.0,303.0,0.522832,-0.041280,0.093830,2.824442,11.319282,-5.176278,149.45258
18,-121.0,87.0,-13.0,303.0,0.522920,-0.043422,0.120679,4.428170,13.408941,-6.438602,149.43219
19,125.0,83.0,-13.0,303.0,0.503433,-0.047386,-0.096221,4.317411,20.852915,-4.936790,149.24911
20,-125.0,83.0,-9.0,303.0,0.534678,-0.061631,0.188421,2.608968,13.961225,-7.704296,149.45912
21,125.0,83.0,-9.0,303.0,0.513260,-0.052428,0.066760,5.698582,15.874985,-3.865228,149.35475
22,125.0,-83.0,-9.0,303.0,0.486183,-0.047774,0.186058,10.967755,10.058026,2.362191,149.86412
23,-125.0,83.0,-5.0,303.0,0.523886,-0.048721,0.209955,8.679339,10.438489,-4.763009,149.57220
24,125.0,83.0,-5.0,303.0,0.516028,-0.041876,0.120914,5.253750,10.873088,-3.495643,149.48495
25,-125.0,-83.0,-5.0,303.0,0.515001,-0.061579,0.267741,9.296250,10.574468,-2.952364,149.77557
26,125.0,-83.0,-5.0,303.0,0.511673,-0.044194,0.142006,3.545773,10.164422,-2.469993,149.54878
27,-125.0,83.0,-1.0,303.0,0.531638,-0.052816,0.209452,12.505682,11.152993,-5.970261,149.67215
28,125.0,83.0,-1.0,303.0,0.513694,-0.052177,0.087786,2.486359,15.391970,-4.623269,149.40034
29,-125.0,-83.0,-1.0,303.0,0.541268,-0.060234,0.373019,8.410166,5.619924,-4.061646,149.72116
30,125.0,-83.0,-1.0,303.0,0.504734,-0.043151,0.108228,8.745763,11.344686,-1.159223,149.56177
31,-125.0,83.0,3.0,303.0,0.518494,-0.055970,0.211933,6.771130,12.627229,-5.033404,149.79381
32,125.0,83.0,3.0,303.0,0.503912,-0.043568,-0.021208,5.288927,16.429728,-3.516314,149.42766
33,-125.0,-83.0,3.0,303.0,0.526842,-0.060755,0.358544,10.564685,7.403382,-2.551649,149.84285
34,125.0,-83.0,3.0,303.0,0.506232,-0.047727,0.158505,5.556976,10.643363,-1.373381,149.62582
35,-125.0,83.0,7.0,303.0,0.527691,-0.057135,0.201064,8.158071,12.758574,-5.827126,149.64796
36,125.0,83.0,7.0,303.0,0.516795,-0.036227,0.005371,6.092728,15.442642,-5.597605,149.33783
37,125.0,-83.0,7.0,303.0,0.501046,-0.049707,0.135678,6.204960,12.427233,-1.256377,149.67050
38,-125.0,83.0,11.0,303.0,0.525951,-0.049383,0.195020,2.226416,12.465546,-6.372564,149.29184
39,125.0,83.0,11.0,303.0,0.517501,-0.056088,-0.062756,5.831921,20.144814,-5.026249,149.09330
40,125.0,-83.0,11.0,303.0,0.494027,-0.042734,0.104575,13.312134,12.887578,0.655210,149.60857
41,-121.0,87.0,14.0,303.0,0.519062,-0.050458,0.130629,8.866804,11.249058,-4.489513,149.65733
42,125.0,83.0,14.0,303.0,0.513650,-0.042421,0.082604,7.047924,13.637304,-4.131079,149.35840
43,-121.0,87.0,18.0,303.0,0.526948,-0.049712,0.118107,10.180771,13.723843,-6.151834,149.40762
44,121.0,87.0,18.0,303.0,0.516383,-0.042760,-0.078075,6.835182,18.593449,-5.996150,149.11462
45,121.0,87.0,22.0,303.0,0.514487,-0.052416,-0.017104,8.839669,17.739445,-3.974470,149.28212
46,-125.0,79.0,22.0,303.0,0.538372,-0.056398,0.188832,11.494978,11.518450,-6.376732,149.56830
47,-125.0,-80.0,22.0,303.0,0.492923,-0.071721,0.221338,9.372469,15.813918,-0.327330,149.61003
48,-125.0,79.0,26.0,303.0,0.525535,-0.050961,0.079917,16.487633,14.433096,-5.601127,149.43370
49,125.0,79.0,26.0,303.0,0.509065,-0.050142,-0.059480,8.381350,18.912422,-4.237181,149.14742
50,125.0,-80.0,26.0,303.0,0.505932,-0.047604,0.106880,8.884654,12.595203,-1.440172,149.49031
51,-121.0,83.0,30.0,303.0,0.538617,-0.054927,0.049736,13.475910,14.212850,-7.321975,149.33493
52,-121.0,-83.0,30.0,303.0,0.522669,-0.059439,0.215534,11.066905,10.321302,-3.414347,149.68271
53,121.0,-83.0,30.0,303.0,0.501175,-0.049473,0.156844,8.833177,11.074309,-0.179782,149.69078
54,-117.0,87.0,34.0,303.0,0.531699,-0.045596,0.104004,8.974957,10.268132,-6.293840,149.55666
55,121.0,83.0,34.0,303.0,0.518694,-0.045954,-0.041124,5.071327,15.605852,-5.288797,149.23856
56,-125.0,75.0,34.0,303.0,0.531715,-0.044551,0.146760,8.896143,8.972930,-5.349886,149.58880
57,-125.0,-76.0,34.0,303.0,0.517257,-0.065974,0.207854,8.683064,12.320985,-3.116711,149.65002
58,125.0,-76.0,34.0,303.0,0.502698,-0.056789,0.134451,8.572441,13.899697,-0.851177,149.58183

In [32]:
df_labels

,x,y,z,vx,vy,vz,px,py,pz,time,distance
25697802,-117.0,87.0,-33.0,0.48,0.01,0.03,0.55,0.52,-1.55,303,150.0
25697865,-121.0,83.0,-33.0,0.49,0.02,0.03,0.55,1.30,-1.20,303,150.0
25697926,121.0,83.0,-33.0,0.48,0.00,0.14,1.04,-3.33,4.84,303,150.0
25697992,-125.0,75.0,-33.0,0.50,0.02,0.03,1.14,2.21,-0.73,303,150.0
25700424,-125.0,-76.0,-33.0,0.49,-0.02,0.04,-1.39,-3.97,-0.94,303,150.0
25700614,121.0,-83.0,-33.0,0.43,-0.03,0.08,3.04,1.08,2.96,303,150.0
25700681,-121.0,83.0,-29.0,0.50,0.01,0.04,0.41,1.18,-1.58,303,150.0
25700807,125.0,79.0,-29.0,0.48,0.01,0.16,1.35,-3.40,4.07,303,150.0
25703369,-121.0,-83.0,-29.0,0.49,-0.01,0.02,-1.73,-3.28,-3.84,303,150.0
25703430,121.0,-83.0,-29.0,0.44,-0.04,0.09,3.18,0.76,2.98,303,150.0
25703560,-125.0,79.0,-25.0,0.51,0.01,0.05,0.33,1.71,-1.41,303,150.0
25703623,125.0,79.0,-25.0,0.48,0.01,0.16,0.82,-2.96,3.76,303,150.0
25706120,-125.0,-80.0,-25.0,0.50,-0.02,0.04,-1.15,-2.66,-4.53,303,150.0
25706183,125.0,-80.0,-25.0,0.43,-0.04,0.09,3.55,0.16,2.65,303,150.0
25706310,121.0,87.0,-21.0,0.48,0.02,0.15,0.62,-2.28,5.24,303,150.0
25708936,-125.0,-80.0,-21.0,0.50,-0.02,0.04,-0.77,-1.96,-5.47,303,150.0
25709065,-121.0,87.0,-17.0,0.50,-0.00,0.07,-0.15,0.35,-1.81,303,150.0
25709126,121.0,87.0,-17.0,0.48,0.02,0.15,0.39,-1.42,5.27,303,150.0
25711881,-121.0,87.0,-13.0,0.50,-0.00,0.08,-0.13,-0.01,-1.71,303,150.0
25712007,125.0,83.0,-13.0,0.48,0.03,0.16,-0.26,-0.39,4.21,303,150.0
25714760,-125.0,83.0,-9.0,0.51,0.01,0.09,-0.20,0.04,-1.31,303,150.0
25714823,125.0,83.0,-9.0,0.49,0.04,0.15,-0.35,0.46,4.11,303,150.0
25717511,125.0,-83.0,-9.0,0.44,-0.05,0.10,2.85,-0.84,2.78,303,150.0
25717576,-125.0,83.0,-5.0,0.50,0.01,0.10,-0.12,-0.45,-1.45,303,150.0
25717639,125.0,83.0,-5.0,0.49,0.04,0.15,-0.32,1.20,3.93,303,150.0
25720264,-125.0,-83.0,-5.0,0.47,-0.04,0.03,1.46,0.49,-7.34,303,150.0
25720327,125.0,-83.0,-5.0,0.45,-0.05,0.10,2.80,-0.93,2.56,303,150.0
25720392,-125.0,83.0,-1.0,0.49,0.02,0.11,-0.05,-0.92,-1.82,303,150.0
25720455,125.0,83.0,-1.0,0.50,0.05,0.15,-0.19,1.78,3.66,303,150.0
25723080,-125.0,-83.0,-1.0,0.47,-0.04,0.02,2.10,1.18,-7.16,303,150.0
25723143,125.0,-83.0,-1.0,0.45,-0.04,0.10,2.87,-0.97,2.35,303,150.0
25723208,-125.0,83.0,3.0,0.48,0.03,0.11,-0.06,-1.35,-2.37,303,150.0
25723271,125.0,83.0,3.0,0.50,0.05,0.14,0.02,2.20,3.31,303,150.0
25725896,-125.0,-83.0,3.0,0.47,-0.04,0.02,2.73,1.90,-6.92,303,150.0
25725959,125.0,-83.0,3.0,0.45,-0.04,0.09,3.03,-0.97,2.14,303,150.0
25726024,-125.0,83.0,7.0,0.47,0.04,0.11,-0.19,-1.72,-2.93,303,150.0
25726087,125.0,83.0,7.0,0.50,0.05,0.14,0.27,2.49,2.94,303,150.0
25728775,125.0,-83.0,7.0,0.46,-0.03,0.09,3.26,-0.95,1.93,303,150.0
25728840,-125.0,83.0,11.0,0.46,0.05,0.11,-0.42,-2.02,-3.36,303,150.0
25728903,125.0,83.0,11.0,0.50,0.05,0.13,0.50,2.66,2.60,303,150.0
25731591,125.0,-83.0,11.0,0.46,-0.02,0.08,3.49,-0.94,1.70,303,150.0
25731593,-121.0,87.0,14.0,0.45,0.05,0.11,-0.40,-3.05,-4.23,303,150.0
25731719,125.0,83.0,14.0,0.49,0.05,0.12,0.66,2.73,2.26,303,150.0
25734409,-121.0,87.0,18.0,0.45,0.06,0.11,-0.66,-3.41,-4.39,303,150.0
25734470,121.0,87.0,18.0,0.49,0.05,0.12,0.50,2.88,1.86,303,150.0
25737286,121.0,87.0,22.0,0.48,0.05,0.11,0.62,2.84,1.65,303,150.0
25737352,-125.0,79.0,22.0,0.44,0.05,0.10,-1.32,-2.56,-3.16,303,150.0
25739912,-125.0,-80.0,22.0,0.47,-0.03,-0.02,5.94,5.33,-5.36,303,150.0
25740168,-125.0,79.0,26.0,0.44,0.05,0.09,-1.63,-3.10,-3.13,303,150.0
25740231,125.0,79.0,26.0,0.48,0.04,0.10,0.70,2.57,1.69,303,150.0
25742791,125.0,-80.0,26.0,0.46,-0.01,0.06,3.88,-1.28,0.71,303,150.0
25742921,-121.0,83.0,30.0,0.44,0.05,0.09,-1.42,-4.28,-4.13,303,150.0
25745609,-121.0,-83.0,30.0,0.48,-0.02,-0.02,6.49,6.96,-5.12,303,150.0
25745670,121.0,-83.0,30.0,0.46,-0.01,0.06,3.17,-1.56,0.84,303,150.0
25745674,-117.0,87.0,34.0,0.45,0.05,0.08,-0.91,-5.24,-5.20,303,150.0
25745798,121.0,83.0,34.0,0.47,0.04,0.08,1.03,2.49,1.85,303,150.0
25745864,-125.0,75.0,34.0,0.44,0.05,0.07,-1.94,-4.06,-2.90,303,150.0
25748296,-125.0,-76.0,34.0,0.48,-0.02,-0.03,6.85,7.26,-3.49,303,150.0
25748359,125.0,-76.0,34.0,0.46,-0.01,0.04,3.76,-1.60,0.23,303,150.0

In [34]:
orig = pd.read_csv("../logs/normalized_input.csv")
gen = pd.read_csv("../logs/normalized_output.csv")

In [35]:
orig

,vx,vy,vz,px,py,pz,distance,x,y,z,time
0,0.25,0.090909,-0.368421,-0.433447,-0.0784,-0.081681,-1.0,-117.0,87.0,-33.0,303.0
1,0.50,0.272727,-0.368421,-0.433447,0.0464,-0.026170,-1.0,-121.0,83.0,-33.0,303.0
2,0.25,-0.090909,0.789474,-0.321957,-0.6944,0.931800,-1.0,121.0,83.0,-33.0,303.0
3,0.75,0.272727,-0.368421,-0.299204,0.1920,0.048374,-1.0,-125.0,75.0,-33.0,303.0
4,0.50,-0.454545,-0.263158,-0.874858,-0.7968,0.015067,-1.0,-125.0,-76.0,-33.0,303.0
5,-1.00,-0.636364,0.157895,0.133106,0.0112,0.633624,-1.0,121.0,-83.0,-33.0,303.0
6,0.75,0.090909,-0.263158,-0.465301,0.0272,-0.086439,-1.0,-121.0,83.0,-29.0,303.0
7,0.25,0.090909,1.000000,-0.251422,-0.7056,0.809675,-1.0,125.0,79.0,-29.0,303.0
8,0.50,-0.272727,-0.473684,-0.952218,-0.6864,-0.444885,-1.0,-121.0,-83.0,-29.0,303.0
9,-0.75,-0.818182,0.263158,0.164960,-0.0400,0.636796,-1.0,121.0,-83.0,-29.0,303.0
10,1.00,0.090909,-0.157895,-0.483504,0.1120,-0.059477,-1.0,-125.0,79.0,-25.0,303.0
11,0.25,0.090909,1.000000,-0.372014,-0.6352,0.760508,-1.0,125.0,79.0,-25.0,303.0
12,0.75,-0.454545,-0.263158,-0.820250,-0.5872,-0.554322,-1.0,-125.0,-80.0,-25.0,303.0
13,-1.00,-0.818182,0.263158,0.249147,-0.1360,0.584457,-1.0,125.0,-80.0,-25.0,303.0
14,0.25,0.272727,0.894737,-0.417520,-0.5264,0.995242,-1.0,121.0,87.0,-21.0,303.0
15,0.75,-0.454545,-0.263158,-0.733788,-0.4752,-0.703410,-1.0,-125.0,-80.0,-21.0,303.0
16,0.75,-0.090909,0.052632,-0.592719,-0.1056,-0.122918,-1.0,-121.0,87.0,-17.0,303.0
17,0.25,0.272727,0.894737,-0.469852,-0.3888,1.000000,-1.0,121.0,87.0,-17.0,303.0
18,0.75,-0.090909,0.157895,-0.588168,-0.1632,-0.107058,-1.0,-121.0,87.0,-13.0,303.0
19,0.25,0.454545,1.000000,-0.617747,-0.2240,0.831879,-1.0,125.0,83.0,-13.0,303.0
20,1.00,0.090909,0.263158,-0.604096,-0.1552,-0.043616,-1.0,-125.0,83.0,-9.0,303.0
21,0.50,0.636364,0.894737,-0.638225,-0.0880,0.816019,-1.0,125.0,83.0,-9.0,303.0
22,-0.75,-1.000000,0.368421,0.089875,-0.2960,0.605075,-1.0,125.0,-83.0,-9.0,303.0
23,0.75,0.090909,0.368421,-0.585893,-0.2336,-0.065821,-1.0,-125.0,83.0,-5.0,303.0
24,0.50,0.636364,0.894737,-0.631399,0.0304,0.787470,-1.0,125.0,83.0,-5.0,303.0
25,0.00,-0.818182,-0.368421,-0.226394,-0.0832,-1.000000,-1.0,-125.0,-83.0,-5.0,303.0
26,-0.50,-1.000000,0.368421,0.078498,-0.3104,0.570182,-1.0,125.0,-83.0,-5.0,303.0
27,0.50,0.272727,0.473684,-0.569966,-0.3088,-0.124504,-1.0,-125.0,83.0,-1.0,303.0
28,0.75,0.818182,0.894737,-0.601820,0.1232,0.744647,-1.0,125.0,83.0,-1.0,303.0
29,0.00,-0.818182,-0.473684,-0.080774,0.0272,-0.971451,-1.0,-125.0,-83.0,-1.0,303.0
30,-0.50,-0.818182,0.368421,0.094425,-0.3168,0.536875,-1.0,125.0,-83.0,-1.0,303.0
31,0.25,0.454545,0.473684,-0.572241,-0.3776,-0.211737,-1.0,-125.0,83.0,3.0,303.0
32,0.75,0.818182,0.789474,-0.554039,0.1904,0.689136,-1.0,125.0,83.0,3.0,303.0
33,0.00,-0.818182,-0.473684,0.062571,0.1424,-0.933386,-1.0,-125.0,-83.0,3.0,303.0
34,-0.50,-0.818182,0.263158,0.130830,-0.3168,0.503569,-1.0,125.0,-83.0,3.0,303.0
35,0.00,0.636364,0.473684,-0.601820,-0.4368,-0.300555,-1.0,-125.0,83.0,7.0,303.0
36,0.75,0.818182,0.789474,-0.497156,0.2368,0.630452,-1.0,125.0,83.0,7.0,303.0
37,-0.25,-0.636364,0.263158,0.183163,-0.3136,0.470262,-1.0,125.0,-83.0,7.0,303.0
38,-0.25,0.818182,0.473684,-0.654152,-0.4848,-0.368755,-1.0,-125.0,83.0,11.0,303.0
39,0.75,0.818182,0.684211,-0.444824,0.2640,0.576527,-1.0,125.0,83.0,11.0,303.0
40,-0.25,-0.454545,0.157895,0.235495,-0.3120,0.433783,-1.0,125.0,-83.0,11.0,303.0
41,-0.50,0.818182,0.473684,-0.649602,-0.6496,-0.506741,-1.0,-121.0,87.0,14.0,303.0
42,0.50,0.818182,0.578947,-0.408419,0.2752,0.522601,-1.0,125.0,83.0,14.0,303.0
43,-0.50,1.000000,0.473684,-0.708760,-0.7072,-0.532117,-1.0,-121.0,87.0,18.0,303.0
44,0.50,0.818182,0.578947,-0.444824,0.2992,0.459159,-1.0,121.0,87.0,18.0,303.0
45,0.25,0.818182,0.473684,-0.417520,0.2928,0.425852,-1.0,121.0,87.0,22.0,303.0
46,-0.75,0.818182,0.368421,-0.858931,-0.5712,-0.337034,-1.0,-125.0,79.0,22.0,303.0
47,0.00,-0.636364,-0.894737,0.792947,0.6912,-0.685964,-1.0,-125.0,-80.0,22.0,303.0
48,-0.75,0.818182,0.263158,-0.929465,-0.6576,-0.332276,-1.0,-125.0,79.0,26.0,303.0
49,0.25,0.636364,0.368421,-0.399317,0.2496,0.432197,-1.0,125.0,79.0,26.0,303.0
50,-0.25,-0.272727,-0.052632,0.324232,-0.3664,0.276764,-1.0,125.0,-80.0,26.0,303.0
51,-0.75,0.818182,0.263158,-0.881684,-0.8464,-0.490880,-1.0,-121.0,83.0,30.0,303.0
52,0.25,-0.454545,-0.894737,0.918089,0.9520,-0.647898,-1.0,-121.0,-83.0,30.0,303.0
53,-0.25,-0.272727,-0.052632,0.162685,-0.4112,0.297383,-1.0,121.0,-83.0,30.0,303.0
54,-0.50,0.818182,0.157895,-0.765643,-1.0000,-0.660587,-1.0,-117.0,87.0,34.0,303.0
55,0.00,0.636364,0.157895,-0.324232,0.2368,0.457573,-1.0,121.0,83.0,34.0,303.0
56,-0.75,0.818182,0.052632,-1.000000,-0.8112,-0.295797,-1.0,-125.0,75.0,34.0,303.0
57,0.25,-0.454545,-1.000000,1.000000,1.0000,-0.389374,-1.0,-125.0,-76.0,34.0,303.0
58,-0.25,-0.272727,-0.263158,0.296928,-0.4176,0.200634,-1.0,125.0,-76.0,34.0,303.0

In [36]:
gen

,x,y,z,time,vx,vy,vz,px,py,pz,distance
0,-117.0,87.0,-33.0,303.0,1.387001,-0.930452,0.729851,-0.147244,1.966347,-1.009968,-2.111413
1,-121.0,83.0,-33.0,303.0,1.267523,-0.939314,2.092760,1.387061,1.116166,-0.433335,-1.479358
2,121.0,83.0,-33.0,303.0,1.026280,-0.790659,0.058670,0.644934,1.840756,-0.437010,-2.136838
3,-125.0,75.0,-33.0,303.0,1.188342,-1.073574,1.351244,1.963358,1.793348,-0.523014,-1.718857
4,-125.0,-76.0,-33.0,303.0,0.803779,-1.241552,2.296577,1.144302,1.638078,-0.042536,-1.110336
5,121.0,-83.0,-33.0,303.0,0.391010,-1.088145,0.809361,1.314329,2.292291,0.223827,-1.514281
6,-121.0,83.0,-29.0,303.0,1.534371,-0.994573,1.538694,0.693092,1.281232,-0.744232,-1.576243
7,125.0,79.0,-29.0,303.0,0.846472,-0.804640,-0.062291,1.042235,2.087030,-0.259990,-1.997928
8,-121.0,-83.0,-29.0,303.0,1.308888,-1.132636,4.342118,1.260562,0.393273,-0.050786,-0.797092
9,121.0,-83.0,-29.0,303.0,0.697517,-0.767914,1.300514,1.128911,0.958293,0.262592,-1.353997
10,-125.0,79.0,-25.0,303.0,1.492963,-1.065926,1.901080,0.944334,1.345343,-0.705991,-1.511624
11,125.0,79.0,-25.0,303.0,1.123507,-0.868731,0.107023,-0.136441,1.952190,-0.637050,-2.293181
12,-125.0,-80.0,-25.0,303.0,0.979289,-1.012097,2.171062,0.876051,1.026693,-0.131555,-1.011235
13,125.0,-80.0,-25.0,303.0,0.697076,-0.832772,1.023302,1.621849,1.416335,0.218195,-1.642410
14,121.0,87.0,-21.0,303.0,1.210868,-0.726915,-0.729576,0.319634,2.140887,-0.835190,-2.271298
15,-125.0,-80.0,-21.0,303.0,0.890257,-1.061324,2.387775,1.442547,1.028693,0.019409,-0.925235
16,-121.0,87.0,-17.0,303.0,1.289429,-0.948162,0.866535,0.854519,1.617867,-0.591831,-2.021668
17,121.0,87.0,-17.0,303.0,0.850150,-0.699900,0.093041,0.129497,1.433792,-0.291980,-1.707516
18,-121.0,87.0,-13.0,303.0,1.688107,-1.065460,2.049420,1.095212,1.044907,-0.676314,-1.716692
19,125.0,83.0,-13.0,303.0,0.966146,-0.845801,-0.260199,0.521400,2.234529,-0.448452,-2.181538
20,-125.0,83.0,-9.0,303.0,1.365852,-1.050836,1.028196,1.598280,1.962810,-0.759668,-1.905943
21,125.0,83.0,-9.0,303.0,0.722053,-0.834320,-0.788213,0.093419,2.185236,-0.315610,-2.046724
22,125.0,-83.0,-9.0,303.0,0.827993,-0.846434,1.535321,1.418457,1.191607,0.185895,-1.526166
23,-125.0,83.0,-5.0,303.0,1.382754,-0.953474,1.588553,2.025118,1.215012,-0.503250,-1.526191
24,125.0,83.0,-5.0,303.0,1.030160,-0.810172,-0.924841,1.464573,2.488780,-0.588851,-2.335984
25,-125.0,-83.0,-5.0,303.0,1.011721,-1.066090,2.873880,0.684743,0.926790,-0.047581,-1.007052
26,125.0,-83.0,-5.0,303.0,1.131178,-0.821869,1.118165,0.143047,1.192453,-0.340487,-1.818314
27,-125.0,83.0,-1.0,303.0,1.432470,-0.958172,1.306795,1.222782,1.598618,-0.740684,-1.941617
28,125.0,83.0,-1.0,303.0,1.105466,-0.777461,-0.331505,0.812830,1.909221,-0.578964,-2.102746
29,-125.0,-83.0,-1.0,303.0,1.281082,-1.313990,3.529536,1.144345,1.303034,-0.276320,-1.129955
30,125.0,-83.0,-1.0,303.0,0.656585,-0.871943,0.709399,1.402224,1.953147,0.053775,-1.671285
31,-125.0,83.0,3.0,303.0,1.664515,-1.058389,1.465432,0.570920,1.373605,-0.828810,-1.961907
32,125.0,83.0,3.0,303.0,0.755753,-0.930902,-1.591087,2.218341,3.096934,-0.384043,-2.465057
33,-125.0,-83.0,3.0,303.0,0.933727,-0.935165,1.762524,0.728124,1.037338,-0.101664,-1.163871
34,125.0,-83.0,3.0,303.0,0.482594,-1.117744,0.612940,1.484493,2.150993,0.242726,-1.619249
35,-125.0,83.0,7.0,303.0,1.290222,-0.917302,1.464060,1.195524,1.208109,-0.533679,-1.322891
36,125.0,83.0,7.0,303.0,1.189917,-0.868478,-0.736864,0.772428,2.257913,-0.590700,-2.570467
37,125.0,-83.0,7.0,303.0,0.510938,-1.071676,0.622302,1.812665,2.192694,0.359956,-1.733833
38,-125.0,83.0,11.0,303.0,1.424383,-0.947847,0.992732,1.394475,1.622722,-0.633254,-2.035463
39,125.0,83.0,11.0,303.0,1.707546,-0.936307,0.673527,-0.132120,1.629290,-0.803820,-2.665930
40,125.0,-83.0,11.0,303.0,1.158677,-0.842877,1.057723,0.732725,1.186953,-0.302127,-1.767012
41,-121.0,87.0,14.0,303.0,1.283253,-0.946801,0.589001,1.470070,1.982339,-0.724506,-2.042758
42,125.0,83.0,14.0,303.0,1.325015,-0.807698,0.174472,0.505849,1.644013,-0.612953,-2.184045
43,-121.0,87.0,18.0,303.0,1.328990,-1.003016,-0.590904,1.469611,2.228068,-0.738115,-2.319692
44,121.0,87.0,18.0,303.0,1.180688,-0.845100,-0.608013,1.014992,2.025334,-0.580539,-2.302031
45,121.0,87.0,22.0,303.0,1.075486,-0.834745,-0.804098,1.029971,2.174262,-0.542551,-2.300760
46,-125.0,79.0,22.0,303.0,1.604490,-0.980762,0.873954,2.104709,1.375089,-0.664042,-1.956368
47,-125.0,-80.0,22.0,303.0,0.993716,-1.174786,1.835233,2.144287,1.544648,-0.137044,-1.253312
48,-125.0,79.0,26.0,303.0,1.312422,-0.941885,0.958838,1.539780,1.656819,-0.556075,-2.034827
49,125.0,79.0,26.0,303.0,1.201251,-1.084979,-1.719397,1.850873,3.069982,-0.657498,-2.861005
50,125.0,-80.0,26.0,303.0,0.917242,-0.874264,0.939442,1.756422,1.647415,-0.002167,-1.754459
51,-121.0,83.0,30.0,303.0,1.439781,-1.108716,0.417458,1.155479,2.299631,-0.889878,-2.247439
52,-121.0,-83.0,30.0,303.0,1.220096,-0.994146,1.906635,2.157827,1.120820,-0.267462,-1.528277
53,121.0,-83.0,30.0,303.0,1.264696,-0.812030,1.253626,0.641530,1.096673,-0.286139,-1.903874
54,-117.0,87.0,34.0,303.0,1.781407,-0.956846,0.152900,1.234374,1.908635,-1.061840,-2.480820
55,121.0,83.0,34.0,303.0,0.951532,-0.963638,-2.150075,1.664370,3.369958,-0.635579,-2.883972
56,-125.0,75.0,34.0,303.0,1.604604,-1.190942,-0.209261,3.187157,2.715581,-1.100185,-2.382593
57,-125.0,-76.0,34.0,303.0,1.182722,-1.122271,1.896458,2.398144,1.304438,-0.184715,-1.512220
58,125.0,-76.0,34.0,303.0,1.138742,-0.733540,0.916385,1.566512,1.177116,-0.156260,-1.930950

In [28]:
df_labels1.to_csv("../dataset/3p6-selected-labels-test.csv", index=False)

In [7]:
df = pd.read_csv("../dataset/wind_forecast_edited.csv")

In [8]:
df.head()

         date  hrs     u     v    ws      wd  farm  time_frame
0  2009070100    1  2.34 -0.79  2.47  108.68     1           1
1  2009070100    2  2.18 -0.99  2.40  114.31     1           2
2  2009070100    3  2.20 -1.21  2.51  118.71     1           3
3  2009070100    4  2.35 -1.40  2.73  120.86     1           4
4  2009070100    5  2.53 -1.47  2.93  120.13     1           5